CREATE TABLE IF NOT EXISTS `tbl_user` (
  `id` VARCHAR(100) NOT NULL, 
  `name` VARCHAR(100) NOT NULL, 
  `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (id) 
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;